<?php

namespace AppBundle\Repository;

/**
 * EntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getEntries()
    {
        $dql = 'SELECT e FROM AppBundle:Entry e order by e.date desc';

        return $this->getEntityManager()->createQuery($dql);
    }
}
